(function () {
  window.RAINFLIX_CONFIG = {
    tmdbApiKey: "dd045c41790ea1b9e9632fa07ffad160",
    tmdbApiBaseUrl: "https://api.themoviedb.org/3",
    tmdbImageBaseUrl: "https://image.tmdb.org/t/p",
    tmdbRegion: "US",
    tmdbCacheTtlMs: 900000,
    tmdbCacheMaxEntries: 60,
    appReadyMinimumMs: 2400,
    appReadyTimeoutMs: 3500,
    analyticsScriptUrl: "",
    analyticsWebsiteId: "",
    analyticsDomains: "",
    vidsrcEmbedBaseUrl: "https://vidsrc.to/embed",
    twoEmbedBaseUrl: "https://www.2embed.cc/embed",
    multiEmbedBaseUrl: "https://multiembed.mov",
    vidlinkEmbedBaseUrl: "https://vidlink.pro",
    vidfastEmbedBaseUrl: "https://vidfast.vc",
    vidsrcMeEmbedBaseUrl: "https://vidsrc-embed.ru/embed",
    vidcoreEmbedBaseUrl: "https://vidcore.org/embed",
    stremioService: {
      enabled: true,
      baseUrl: "http://127.0.0.1:11470",
      checkTimeoutMs: 5000,
      playbackTimeoutMs: 60000,
    },
    webTorrent: {
      enabled: true,
      metadataTimeoutMs: 35000,
      playbackTimeoutMs: 75000,
      maxConns: 40,
      uploadLimitBps: -1,
      trackers: [
        "wss://tracker.openwebtorrent.com",
        "wss://tracker.btorrent.xyz",
      ],
    },
    torrentio: {
      enabled: false,
      baseUrl: "https://torrentio.strem.fun/sizefilter=10GB",
      manifestUrl: "",
      requestTimeoutMs: 25000,
      playbackTimeoutMs: 30000,
    },
    yastream: {
      enabled: false,
      baseUrl: "https://yastream.tamthai.de",
      manifestUrl: "",
      requestTimeoutMs: 25000,
      playbackTimeoutMs: 25000,
      options: {
        catalogs: [
          "kisskh.series.Korean",
          "kisskh.movie.Korean",
          "kisskh.movie.Chinese",
          "kisskh.series.Chinese",
          "kisskh.movie.US",
          "kisskh.series.US",
          "kisskh.movie.Thai",
          "kisskh.series.Thai",
          "kisskh.movie.Philippine",
          "kisskh.series.Philippine",
          "kisskh.movie.Japanese",
          "kisskh.series.Japanese",
          "kisskh.movie.Hongkong",
          "kisskh.series.Hongkong",
          "kisskh.movie.Taiwanese",
          "kisskh.series.Taiwanese",
          "onetouchtv.series.Korean",
          "onetouchtv.series.Chinese",
          "onetouchtv.series.Popular",
          "onetouchtv.series.Thai",
          "kisskh.series.Search",
          "kisskh.movie.Search",
          "onetouchtv.series.Search",
          "idrama.series.iDrama",
          "idrama.series.Search",
        ],
        catalog: ["kisskh", "onetouchtv"],
        stream: ["kisskh", "onetouchtv"],
        nsfw: false,
        info: false,
        poster: "rpdb",
        mfpUrl: "",
        tbKey: "",
        mfpPass: "",
      },
    },
  };
})();
